before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: APAIhS+NLrzpyTg+/m/MumlTrTU9xefMI7NATyF1Q6sMfFOcr2zu1seujlz6eaXULHLHaJb5vU+HPeXMbsDLVf06Wy9TirFi3CuqQfTjOvxs3Bu5Kbj9aNT4ogYsBEMURr1bZRcrVkt6GYIPoNom3wvW40WoCLb2EgjQ+C+rLzsjq+2VhDUM1l0q6bHJwOXT31QQ52w/SzAVH/4RV7VzX2Mh4OkrWS0FpfnrqUNrrwWEhXvIOhRstJzrONmAB2YfluzOKb7iOJOWa8T114GnqVVfnTjab4xXNTI9drDtZyxLtGoNASXAKcBAqqHqJGqnQHOVCFTElM5bAU7VTUDqCzvclAKktroVakXjOlR2JmYwkEWwwetBGymUSKsUGtbC8Pm3xNouCe5w9uY5yTauoWwaJGdP7VdkSY1TfmfUD65Yz2vBwYNmEjmVmfdFavQX2zplCDoDhNgdLl74F6ppNLY5zfNBQEShVNp26ORkjFqkHAzNI2jT5ja/QjypJ4R2EjKyVMHdXwe7+XvQ1PBo+njuZWil7Ko8O22a6TtnzAPA9TWeQ49Fu5ui/GZEXttADE9+lOFXlJ8fvFkR3ux04dFDxdtQvVfRO7mdRO5jgMbxz4s9KREBAixtm5B6xCwL4OXULtX0e4Fqj1kk0bEANVpZyblwUjRnjAsN9Ey1hNI= # CRYPTO_AES_KEY
language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
